name: neonnekko
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.3

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.12.0
  provider: ^6.1.2
  app_links: ^6.2.0
  intl: ^0.20.2
  http: ^1.6.0
  shared_preferences: ^2.5.4
  shadcn_ui: ^0.43.0
  flutter_rating_bar: ^4.0.1
  image_picker: ^1.2.1
  cached_network_image: ^3.4.1
  flutter_svg: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
